### ISSUE TITLE
openSUSE Brand Name refresh

### ISSUE THREAD

**Issue by hellcp** [openSUSE/branding#112]
While `openSUSE` is great, it has an issuee:

Name is associated with SUSE verbatim

So what are the requirement for a name?
* Associated with SUSE by colour, chameleon, sound or whatever else
* Works well with other existing brands under openSUSE (Tumbleweed, Leap, Kubic, MicroOS, OBS, Kiwi etc)

https://lists.opensuse.org/opensuse-project/2019-06/msg00001.html

**Comment by probonopd** [comment]
> Name is associated with SUSE verbatim

Why is this an _issue_? Does SUSE have a problem with it now?

**Comment by hellcp** [comment]
@probonopd  I added a link to mailing list discussions, where this started off. It's associated with foundation discussions and trademark issues resulting from this.

**Comment by MrSunshyne** [comment]
I would suggest `GeckOS`. although it has some [history](https://en.wikipedia.org/wiki/GeckOS).

**Comment by hellcp** [comment]
Yeah, "history" will be problematic, and openSUSE project does more than distributions nowadays ;)

**Comment by marinho8bit** [comment]
would not like to give up the "open". I think it's the charm of the name.

openS
openSU
openUP
openSYS
openLinux

**Comment by probonopd** [comment]
openOS

**Comment by bobblkabb** [comment]
**OS05**, [pronounced _osos_] openSUSE or Operation System (beware of copy right ;-) + start year of the opensuse project (2005)

**Comment by coolo** [comment]
Guys, before you make this completely useless: the distributions are called Tumbleweed and Leap. This is about a brand name of the project.

**Comment by elchevive** [comment]
Iguana (a kind of lizard)

**Comment by crowbyte** [comment]
Hi guys,

I already put my 2 cents on some more channels, but as I got to know that this is the right place for suggesting names, here is my idea on a new name:

How about naming the foundation "Leap Foundation". Leap is tied and connected to openSUSE and therefore to SUSE, but still unique and earned some good reputation for being an excellent enterprise class operating system.
We might then think about a renaming of Tumbleweed. But to be honest I never liked the name anyways. My suggestion would be to call it "Leap Infinity" or "Leap infin8" or something alike.

**Comment by hellcp** [comment]
@crowbyte I actually discussed changing Leap branding to other colour for the sake of separating Leap and openSUSE branding as far apart as possible during my oSC talk, because from the point of view of the project, Leap, Tumbleweed (and soon Kubic and MicroOS) are equally important and equally supported. Naming the foundation after one of the distros will just make everything confusing yet again. The Leap distribution also wasn't named just "openSUSE" by coincidence, it's one of many distributions we make, we needed to seperate the project from the distros to have some more space for Tumbleweed (and now for Kubic and MicroOS).

**Comment by hellcp** [comment]
Maybe a little bit offtopic, but worth mentioning some of Reddit's ideas from /r/linux
[![The last of serious suggestions](https://user-images.githubusercontent.com/30577011/58948225-ebeda480-8789-11e9-99ad-2e22585b356d.png)](https://www.reddit.com/r/linux/comments/bwf3p2/opensuse_community_is_having_a_discussion_on/epzqwdv/)
[![That's just additional work for Douglass though](https://user-images.githubusercontent.com/30577011/58948324-26efd800-878a-11e9-9bce-ef0073461f27.png)](https://www.reddit.com/r/linux/comments/bwf3p2/opensuse_community_is_having_a_discussion_on/epxq6ed/)
[![There is also always Grosz from Polish equivalent](https://user-images.githubusercontent.com/30577011/58948417-5ef71b00-878a-11e9-8187-e292671b6116.png)](https://www.reddit.com/r/linux/comments/bwf3p2/opensuse_community_is_having_a_discussion_on/epy371r/)
[![Associations with Kevin Spacey might be harmful](https://user-images.githubusercontent.com/30577011/58948508-92d24080-878a-11e9-8e8d-13cdec725e0c.png)](https://www.reddit.com/r/linux/comments/bwf3p2/opensuse_community_is_having_a_discussion_on/epy8fd3/)
[![Tongue in cheek](https://user-images.githubusercontent.com/30577011/58948591-bbf2d100-878a-11e9-9400-c5a487efa003.png)](https://www.reddit.com/r/linux/comments/bwf3p2/opensuse_community_is_having_a_discussion_on/epyhtcu/)

**Comment by crowbyte** [comment]
@hellcp 
Missed that obviously. Nonetheless, I think it would be a nice name for the foundation. Although I agree, that there might be some confusion on distro and foundation / community names.

**Comment by crowbyte** [comment]
https://news.nationalgeographic.com/2018/01/chameleon-bones-florescent-ultraviolet-light-spd/
"[...] On January 15, a team of German researchers published a paper showing that the bones of chameleons glow under UV light. They tested the light rays on 160 specimens that spanned 31 species of Calumma chameleons, [...]"
So how about adapting the glow in a logo and call the foundation Calumma?

Mainly joking, but not the worst idea. ;-)

**Comment by athano** [comment]
@hellcp

**Comment by hellcp** [comment]
Yeah, the general idea this far has been either chameleon related or green related

**Comment by athano** [comment]
> 
> 
> Yeah, the general idea this far has been either chameleon related or green related

Yes; that's why I propose the name of:
**GEKO**

**Comment by athano** [comment]
An idea like this I propose with the new name respecting the previous colors

![geckos](https://user-images.githubusercontent.com/24998848/58981260-4806f780-878f-11e9-9ff1-892686ee83d5.png)

**Comment by hellcp** [comment]
Colours will most likely have to be changed as well, the current palette isn't really fulfilling its role as well as I would hope it could. Also please, no OS in the name ;)

**Comment by marinho8bit** [comment]
> Colours will most likely have to be changed as well, the current palette isn't really fulfilling its role as well as I would hope it could. Also please, no OS in the name ;)

What do you think of openS and openSU?

**Comment by athano** [comment]
> 
> 
> Colours will most likely have to be changed as well, the current palette isn't really fulfilling its role as well as I would hope it could. Also please, no OS in the name ;)

I understand we are going to remove that from "OS" and I also think it is excellent to change the color palette; I would recommend that we do an exercise:

Let's say that words or sentences represent the current openSUSE community, for example:
"Community, friendship, innovation."

Or a prayer like:
"For my openSUSE it represents one of the most careful and stable distros in the field of Linux communities"

For exposing some examples. From that we take the keywords, to develop a brand concept...

**Comment by hellcp** [comment]
One thing openSUSE certainly inherited from SUSE back in the day when it was first formed was the "Have a lot of fun" tagline, since then we have seen that expanded to include "Get it! Discover it! Create it!" and roots of that are the beginnings of openSUSE where this was basically the entire scope of the project:
* Get it, distribution
* Discover it, wiki
* Create it, OBS

Then there was "Linux for open minds" and now we have "The makers' choice". AFAIK the "The makers' choice" slogan was chosen based on some research into who actually uses openSUSE.

But if we consider the community itself, I do believe we still do have the "Have a lot of fun" vibe, rather than more business oriented "The makers' choice" in us.

**Comment by probonopd** [comment]
> Fun

would be a good name?

Have a lot of fun!

**Comment by marinho8bit** [comment]
@athano Would not that be the new logo?

https://github.com/openSUSE/branding/issues/93#issuecomment-499207398

**Comment by jaypatelani** [comment]
![Screenshot_20190607-192120~2](https://user-images.githubusercontent.com/17174485/59109045-d3b58b00-892b-11e9-9f8a-a2b8a865d340.png)
Have already shared this idea with rbrownsuse .

Another name : Harit 
Harit Means green 
Link showed in screen shot https://www.jewelsforme.com/emerald-meaning

**Comment by cyntss** [comment]
>But if we consider the community itself, I do believe we still do have the "Have a lot of fun" vibe, rather than more business oriented "The makers' choice" in us.


I see too much focus on the "community" as a group of friends, and too little interest in making "openSUSE the best operating system and open source solution" available.
Part of being open source is building a nice environment and group of individuals to develop, learn, and have fun together, yes, but more importantly, it is to have a community which best interest at heart is to see the product grow and become successful. Unfortunately successful doesn't come from "have fun with us" but from "use the best software you'll ever use again".

I ask once again what is the problem the ones proposing a new name see in the current openSUSE?. Because every time I mention openSUSE to friends they are like "wow! yes".

I'm all for updating the logo (not in a disruptive way), but the name? Not a good idea.

**Comment by crowbyte** [comment]
@cyntss 
The openSUSE board has made the decision to form a foundation as a legal entity for the community to ease things like contributions, cooperations etc.
But as a legal entity the foundation has a legal issue using copyright protected trademarks as we currently do with having SUSE in openSUSE. I know, there are options to possible work around those legal issues. This has been discussed in detail on the mailing lists the last few days. Still, it's unlikely that SUSE will grant an unlimited and irrevocable right to use their name/trademark/copyrights. So there will be limitations to the use and this will make the process of building a foundation a very tricky and complicated one with long going negotiations with SUSE.

So, that being said, the easiest way to avoid those complicated negotiations would be to use another name for the foundation and therefore change the project name.

**Comment by probonopd** [comment]
> Why is this an issue? Does SUSE have a problem with it now?

https://www.heise.de/newsticker/meldung/openSUSE-Projekt-will-eigene-Foundation-und-erwaegt-Namens-und-Logo-Aenderung-4444959.html says:

> SUSE purchase by EQT as uncertainty factor
>
> The idea of outsourcing the openSUSE project into a separate organization was discussed at two board meetings on April 2 and 16 and at the openSUSE Conference. It became clear that the acquisition of SUSE by the financial investor EQT also played a role in the considerations.
> 
> Board member Simon Lee, for example, suggested that a resale of SUSEEs in the future was quite likely given EQT's business model. It is uncertain whether future buyers will value the open source project in the same way. That's why it makes sense to discuss changes now that the relationship between openSUSE and SUSE is good.
> 
Translated with www.DeepL.com/Translator

While I don't know how accurate the reporting is, that explanation does kinda make sense for me.

**Comment by simonsan** [comment]
I like openSusie really much. Ok, let's be serious. If you want to stay with the same species I would propose changing the name to openCameo derived from "Chamaeleo" also found in Europe.

**Comment by spidermex** [comment]
My two cents
- openUSE
- openUSES
- opensUSE

**Comment by jaypatelani** [comment]
OpenDSAS : Development of Systems and Software.

**Comment by jaypatelani** [comment]
"Titli" : Means Butterfly 
Logo can be Green ButterFly.

**Comment by bobblkabb** [comment]
I like the "Titli" approach but I got another logo idea in my mind..
;-P

**Comment by jaypatelani** [comment]
"Four Green" 
Logo can be four shades of green squares elegant and simple.

**Comment by wnereiz** [comment]
"open" is not the must as part of the name, why? see **[Explaining Why We Don't Endorse Other Systems (openSUSE)](https://www.gnu.org/distros/common-distros.en.html#openSUSE)**:

> openSUSE offers a repository of nonfree software. This is an instance of how **[“open” is weaker than “free”](https://www.gnu.org/philosophy/open-source-misses-the-point.html)**.

I prefer "libre"

**Comment by letsfindaway** [comment]
As the discussion seems to start again I also want to add my opinion.

The very first question is what we gain from a name change and what we lose. While I'm quite sure what we lose I'm not certain about what we gain.

The name openSUSE stands for an open, rock-solid, powerful and community driven distribution. The name and the logo have good visibility and excellent reputation. This is a treasure that we must not risk recklessly.

I have seen really big companies investing millions in campaigns to communicate a name change - and in my perception they still failed, and in the end they lost part of their visibility in the public. For openSUSE that would be a bitter setback.

And to all those making proposals here: When suggesting a new name and logo, it is not about what **you** like, what you think is cool or whatever arguments you have. It is about what **the others** think and how a new brand is perceived in the public and in the community, be it experienced openSUSE enthusiasts, users of other distributions or newcomers. Seeing all these proposals and discussions about animals and minerals I really miss the factor of perception in the public.

Coming back to my initial question: Do you really have a clear answer to what we expect from a change, besides of "may make things easier"? Don't throw away a huge asset for some unclear expectations!

**Comment by letsfindaway** [comment]
Thanks for sharing your expectations. When considering each of them I personally came to the conclusion that they could all be achieved with smaller changes:

> * making it clear we are not SUSE to the general public

could be achieved with some addition like "The openSUSE Foundation" or similar.

> * making the capitalization a little bit more standard for the general public

I don't see this as a major issue. It is a distinguishing point I like. Of course this is a personal opinion. The proposed addition "The openSUSE Foundation" would at least inhibit the automatic capitalization performed by some word processors when the name is at the beginning of a sentence.

> * further distancing the project from being distributions only

The distance of a distribution from the project cannot be achieved by changing the name of the project. We still would have to make clear what the difference between Leap or Tumbleweed and whatever the name of the foundation is. Like using "Leap - a distribution of The openSUSE Foundation" or similar.

> * retaining the general branding vibe

Of course this is not a reason for a name change, but something you hope can be preserved ;)

So still I would like to have "openSUSE" as part of the name of the foundation.

**Comment by hellcp** [comment]
> Thanks for sharing your expectations. When considering each of them I personally came to the conclusion that they could all be achieved with smaller changes:
> 
> > * making it clear we are not SUSE to the general public
> 
> could be achieved with some addition like "The openSUSE Foundation" or similar.
> 
> > * making the capitalization a little bit more standard for the general public
> 
> I don't see this as a major issue. It is a distinguishing point I like. Of course this is a personal opinion. The proposed addition "The openSUSE Foundation" would at least inhibit the automatic capitalization performed by some word processors when the name is at the beginning of a sentence.

That's already a thing, the project is called [`The openSUSE Project`](https://en.wikipedia.org/wiki/The_openSUSE_Project), but nobody refers to it as such, with the exception of some articles. It is simply way too long. In case of Foundation, we would have `The openSUSE Project` backed by `openSUSE Foundation` or `The openSUSE Foundation`. It doesn't solve the core issue, in many languages `Title Case` enforces the rule to capitalize principal words, and openSUSE is a principal word in the context of titles like `The openSUSE Project`.

> > * further distancing the project from being distributions only
> 
> The distance of a distribution from the project cannot be achieved by changing the name of the project. We still would have to make clear what the difference between Leap or Tumbleweed and whatever the name of the foundation is. Like using "Leap - a distribution of The openSUSE Foundation" or similar.

I did start removing openSUSE from the graphical representations of our distribution logos. In case of Tumbleweed, MicroOS and Kubic you will get to see logos in plymouth or gdm don't mention openSUSE at all. It's a slow process, but it will pay off whether the project name changes or not.

**Comment by wnereiz** [comment]
> And to all those making proposals here: When suggesting a new name and logo, it is not about what **you** like, what you think is cool or whatever arguments you have. It is about what **the others** think and how a new brand is perceived in the public and in the community, be it experienced openSUSE enthusiasts, users of other distributions or newcomers. Seeing all these proposals and discussions about animals and minerals I really miss the factor of perception in the public.
> 
Thank you. Your words are inspiration. Once we decide to change the name, why don't we collect suggestions by a questionnaire for our users (non-member) and other peoples even have not used openSUSE?

**Comment by jaypatelani** [comment]
@wnereiz something like this?

https://drive.google.com/file/d/1ERi7mWy_1lXnTe9ZzLq10II79Axr2BUC/view?usp=drivesdk

**Comment by wnereiz** [comment]
@jaypatelani Kind of survey like that. Thank you.

There is another benefit. The questionnaire is not only for collecting ideas, it is also a chance to spread news that we decide to change name and logos. Make it known by more people, even someone don't know it before.

**Comment by marinho8bit** [comment]
openware

**Comment by marinho8bit** [comment]
openware (openSUSE + Slackware)

**Comment by wnereiz** [comment]
> An idea like this I propose with the new name respecting the previous colors
> 
> ![geckos](https://user-images.githubusercontent.com/24998848/58981260-4806f780-878f-11e9-9ff1-892686ee83d5.png)

I like your idea. Maybe we should promote it through more ways, eg. mailing list

**Comment by bobblkabb** [comment]
There's already a distribution called [GeckoLinux
](https://distrowatch.com/table.php?distribution=gecko)

**Comment by jaypatelani** [comment]
CSiG: Computer Systems innovation Group.

**Comment by wnereiz** [comment]
> There's already a distribution called [GeckoLinux ](https://distrowatch.com/table.php?distribution=gecko)

It seems almost dead
https://github.com/geckolinux/geckolinux-project/issues/113

**Comment by jaypatelani** [comment]
@wnereiz not dead at all :) author mentioned that in OpenSuse mailing list..

**Comment by wnereiz** [comment]
@jaypatelani Yes, I know, but it is still based on Leap 15.0. And the support will be stopped.

**Comment by jaypatelani** [comment]
Unitinity = Unity + Infinity

**Comment by ish-sookun** [comment]
Folks, we're asking suggestions for a project name, not a distribution name. Do not think of openSUSE the Linux distribution but think of the openSUSE Project. The project name will also become the new foundation's name if the community votes "Yes" for the project name change.

**Comment by hellcp** [comment]
The vote ended at:

- Yes    42
- No    225

**Comment by ghost** [comment]
+1 GeekOS ;)
