### ISSUE TITLE
JPEG quality setting insanely high (100)

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/branding#115]
The quality setting has changed from 95 to 100 here:
https://github.com/openSUSE/branding/commit/8513661ccd8e8c4ebf8bd975c209eeb688c8a0a0

Even reducing the quality to 99 reduces the image size by about 50%, which is a significant reduction, as the 5K wallpaper alone is 3.2 MByte.

There is no apparent visual loss going to 99...95, and even 100 is lossy. As currently 2x2 color subsampling is applied, using a quality of 95 and 1x1 (i.e. no) color subsampling results in better quality (no color fringes) and smaller images.

**Comment by vinzv** [comment]
Just for my understanding: is there any advantage gained from smaller images besides saving disk space?

**Comment by hellcp** [comment]
Unlike the new Plasma wallpaper, this wallpaper does not have much static, which makes it a prime candidate for not being as big as it is. There is no reason why it should be this big.

**Comment by coolo** [comment]
> Just for my understanding: is there any advantage gained from smaller images besides saving disk space?

Loading times. Not only the time it takes to read the blocks from disk, but also the pure DCT conversion will have to read all these 0s you put in there. On modern Laptop hardware you will most likely not be able to measure this (today's CPUs are made for jpg :), but doubling the effort for 1% quality doesn't sound right.

**Comment by vinzv** [comment]
> On modern Laptop hardware you will most likely not be able to measure this (today's CPUs are made for jpg :), but doubling the effort for 1% quality doesn't sound right.

Okay, that's what I somehow assumed. I just want sure if there's anything else. Thanks for clarifying!

We really should implement this then.

**Comment by vinzv** [comment]
Fixed via #119. Therefore this issue can be closed.

**Comment by StefanBruens** [comment]
Please reopen until applied to SLE/Leap 15.x > 15.2 and Tumbleweed ...
