### ISSUE TITLE
Tumbleweed 5K wallpaper is just a big prerasterized png image

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/branding#116]
$> grep png desktop-*.svg | head -c 120

desktop-5120x3200.svg:<image id="image43" width="5120" height="3200" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANS

**Comment by hellcp** [comment]
Yup, I didn't have powerful enough hardware to rescale it in inkscape, so I used rescaling in librsvg, which renders at higher res to png and embeds into svg.

**Comment by StefanBruens** [comment]
So, why not just use
$> rsvg-convert raw-theme-drop/desktop-3840x2400.svg -w 5120 -o tmp-wallpaper.d.png

Same result ...

**Comment by hellcp** [comment]
I was also too lazy to change stuff in the Makefile :P

**Comment by lkocman** [comment]
I'd like to close this issue in favor of #135 I'll make the 5k requirement in the request summary and will reference this issue for historical reasons.
