### ISSUE TITLE
openSUSE Leap 15.5 wallpaper refresh

### ISSUE THREAD

**Issue by lkocman** [openSUSE/branding#132]
A tracker for the effort recently briefed on Community meeting https://etherpad.opensuse.org/p/weeklymeeting20211207
SUSE Branding team would help us to make wallpapers with SLES look and feel.

The topic of a new background was for the first time discussed I believe in 15.2, I think 15.4 based on SLES 15 SP4 which is a feature release could deliver such a welcome change to our desktop users.

Expectation is to have backgrounds in Leap 15.4 prior Feb 23rd which is the date when we'd like to have a Leap 15.4 Beta build done. https://en.opensuse.org/openSUSE:Roadmap

**Comment by hellcp** [comment]
I was considering making wallpapers when Leap 16 was going to release, except I didn't expect Leap 15 to go on for so long. I'm fine with new wallpapers as long as they don't look like the initial SLE 15 SP3 ones. ;)

**Comment by lkocman** [comment]
Hehe :-) understood. We're still in the middle of discussion, stay tuned!

**Comment by ivoermejo** [comment]
![dark wallpaper 01](https://user-images.githubusercontent.com/66246145/149653631-0288cf16-5223-458f-b079-e76bf45e591e.jpg)
![dark wallpaper 02](https://user-images.githubusercontent.com/66246145/149653633-cd6c75f3-bf44-44b6-94c8-f0da694edc81.jpg)
![dark wallpaper 03](https://user-images.githubusercontent.com/66246145/149653635-dcda367a-ea85-4db1-a34f-48e625773014.jpg)

3 dark wallpapers

**Comment by ivoermejo** [comment]
![musician dark wallpaper](https://user-images.githubusercontent.com/66246145/149653679-dc1816a7-022d-4db8-bd0f-6f7479959f0a.jpg)

**Comment by hellcp** [comment]
The first three don't use our branding colours, and as a personal note I find the logo entirely unnecessary, the last one isn't made in accordance to our wallpaper guidelines from the wiki.

**Comment by HorrorPills** [comment]
![openSUSE](https://user-images.githubusercontent.com/21268783/179551753-e50b652e-fd9a-4295-8d4c-a3c94bb50588.png)

**Comment by HorrorPills** [comment]
![openSUSE_1](https://user-images.githubusercontent.com/21268783/179558452-e5872ce1-b50d-4464-b544-89d1ba9d8f7c.pn
![openSUSE_1_noLogo](https://user-images.githubusercontent.com/21268783/179558506-cd4ca9c6-02f9-4772-b4a4-163289e1382c.png)
g)
![openSUSE_1_logo_bottom](https://user-images.githubusercontent.com/21268783/179558532-c8dbbaa4-618c-46c0-9f11-48dbb0e01d3e.png)

**Comment by HorrorPills** [comment]
In Green 4k!

![openSUSE_1_logo_bottom](https://user-images.githubusercontent.com/21268783/179558680-802e7ec6-c59a-473e-8401-b58f187bf65b.png)
![openSUSE_1_noLogo](https://user-images.githubusercontent.com/21268783/179558715-f5021917-9cd5-49ec-99f4-cf5e2ece2276.png)
![openSUSE_1](https://user-images.githubusercontent.com/21268783/179558727-93e13e58-0d26-42bc-9248-8fa14b7e8b59.png)

**Comment by hellcp** [comment]
Ignoring that it doesn't follow our wallpaper guidelines, the image is taken from the internet without paying for it (it would likely be fairly expensive to buy an image like this for use as our wallpaper)

**Comment by lkocman** [comment]
Re-raising the request with SUSE Branding team for 15.5, this time with a bigger heads up (several months).

**Comment by lkocman** [comment]
A thought from our early rel-eng meeting chat as well as from the community weekly meeting on Tuesday.

![comparison](https://user-images.githubusercontent.com/510119/187721464-5358d2fd-eafc-45d2-b1e9-e32e6f0f82e3.png)

I suppose SUSE branding team would be okay with us mimic-ing theirs (I did send Spencer an email).

**Comment by hellcp** [comment]
I would say that we should probably do a distribution logo in the corner instead of the project logo, since it's the wallpaper for the distribution. I kind of wonder if we shouldn't also try to aim for colours that are associated with the distribution instead of the project too, but that may be harder to do

**Comment by lkocman** [comment]
another option would be to place it into spaces in between bars (e.g. tiny chameleons dots or similar)

**Comment by lkocman** [comment]
@hellcp I like the distribution idea, as I'm pretty sure we can find more "contrastful" colors. Do we have defined color pallet for Leap? Or would colors from get-o-o/leap work?

**Comment by lkocman** [comment]
Otherwise my svg is here (feel free to tweak it) 
![FHD_1920x1080](https://user-images.githubusercontent.com/510119/187742819-37e8f777-ee2c-4a3c-bfb7-719c89fe1a8a.svg)

**Comment by hellcp** [comment]
> @hellcp I like the distribution idea, as I'm pretty sure we can find more "contrastful" colors. Do we have defined color pallet for Leap? Or would colors from get-o-o/leap work?

That's the only place we really use those colours, but there was a PR to use those colours with logo in the artwork repo too

**Comment by ddemaio** [comment]
@lkocman super nice. That totally makes sense. @kwwii fyi  👀

**Comment by lkocman** [comment]
@hellcp get-o-o page to Leap would be limited to basically four colors #fbc75d, #21a4dfff (active links) #000000 #fffffff, and their respective 90% 80% ... variants just like in our branding.

Let me try to use the leap yellow  in contrast with  the main project colors. Since the contrast with orange on the SLES wallpaper looks pretty neat.


![comparison_2](https://user-images.githubusercontent.com/510119/187863145-753b9dce-6e6f-4f36-88cb-05c7c62bd821.png)

**Comment by lkocman** [comment]
And then experiment with idea from the call (fill spaces with geekos). I did only two smallest ones as otherwise there would be quite a gap unless we'd resize it or similar. 
![experiment](https://user-images.githubusercontent.com/510119/187863340-120d6af5-20a7-4cb4-a75b-62a3b5db80d2.png)

**Comment by lkocman** [comment]
Actually after checking also the get-o-o landing page that would be:

#54533c #4b3a2a #fbc75d #21a4dfff #000000 #fffffff

**Comment by lkocman** [comment]
Quite a brave experiment with colors mentioned above. I have to admit it looks cooler than I thought! Please note Doug's experimental Leap logo in spaces. I did use geeko for the single large gap.


![yellow_experiment_new](https://user-images.githubusercontent.com/510119/187867281-f9551648-e114-4788-ab0b-a4a14e7f270a.png)

**Comment by lkocman** [comment]
The logo is too close to gnome-panel imho, we should put it bit lower.

**Comment by lkocman** [comment]
Corrected logo placement as well as reduced amount of Leap logos. Sometimes more =! better

![FHD_1920x1080_yellow](https://user-images.githubusercontent.com/510119/187873934-b638b3f3-9240-40e6-8132-94dc70571475.svg)

**Comment by lkocman** [comment]
The original svg with better logo placement

![FHD_1920x1080](https://user-images.githubusercontent.com/510119/187889549-c65bee86-aeb0-46c4-bbb6-5529f88ef1e3.svg)

**Comment by hellcp** [comment]
I think it would be nice to include both light and dark mode wallpaper, since it's otherwise a bit bright
![Screenshot from 2022-09-01 12-55-54](https://user-images.githubusercontent.com/30577011/187897955-ba65817e-c58f-43ca-bac2-9d8121f727e2.png)

**Comment by hellcp** [comment]
There's also a bit bolder of a way to do it
![Screenshot from 2022-09-01 13-09-20](https://user-images.githubusercontent.com/30577011/187900119-f18af7ec-22ae-4627-a64c-ed620d9a29da.png)

**Comment by lkocman** [comment]
Yes the yellow can hurt if you have brightness on 100%. Otherwise it looks fine on default brightness settings on my external display. I think offering multiple variants would bre super cool.

**Comment by lkocman** [comment]
Great news! We have a SUSE brand team approval for such design. So let's get this real.

@ddemaio how about voting for particular color combinations on survey-o-o? Alternative would be to vote on today's community meeting (we could mention that voting ahead and get some more visitors) :-)

We would vote for one of

1. This combination from Leap get-o-o colors dark/light

![187897955-ba65817e-c58f-43ca-bac2-9d8121f727e2](https://user-images.githubusercontent.com/510119/187942043-61edf9c4-d0ef-484f-b8fd-dfa3c4ec8804.png)

2. This alternative combination from Leap get-o-o colors  dark/light

![187900119-f18af7ec-22ae-4627-a64c-ed620d9a29da](https://user-images.githubusercontent.com/510119/187942874-fbe6b052-cb75-4cf1-a55d-165b6c65355a.png)


3. a single combination of project colors 
![FHD_1920x1080_new_logo](https://user-images.githubusercontent.com/510119/187942758-7e790c90-c207-43e0-9898-1ca52e04821a.png)

Additionally I'd ask a yes/no question if we should keep the little geeko in the space or not (no matter the chosen combination). I kept on switching wallpaper constantly on my screen and to me the geeko variant makes me bit more happy.

**Comment by hellcp** [comment]
I'm trying out some more concepts that would work better applied to both leap and Tumbleweed, with the idea being that we could do a similar tessellation with triangles to get a nice Tumbleweed wallpaper too
![falling-light](https://user-images.githubusercontent.com/30577011/187962212-656ab006-684e-4d58-86d1-0593915bcb50.png)
![falling-dark](https://user-images.githubusercontent.com/30577011/187962216-db408544-1642-43bf-800f-99f248301a63.png)

**Comment by hellcp** [comment]
Got some feedback that the wireframe might not be the way to go, but may as well play around and see what works best
![falling-full-soft-coloured-light](https://user-images.githubusercontent.com/30577011/187982356-946a84b4-b77c-4234-8f45-860a18f35b40.png)
![falling-full-hard-coloured-wireframe](https://user-images.githubusercontent.com/30577011/187982360-0fa8ec59-fa64-42b1-b5d2-dac0d50053a4.png)

**Comment by lkocman** [comment]
The idea was actually to provide same look and feel as SLES. This would not go that way, although I really like the yellow one above.

**Comment by lkocman** [comment]
The lines that we have could transition to tumbleweed as well, in case we'd shape the lines to infinity symbol e.g. two interconnected circles ... I could see how that could be done.

**Comment by hellcp** [comment]
If we use the new Leap logo, might as well use the new Tumbleweed logo too, which would be a triangle, I was gonna make the triangle version of this wallpaper too

**Comment by lkocman** [comment]
@hellcp How about using one of the color schemes with line as default (we'd do formal voting). And take the time until e.g. around december) to supply perhaps 3d flipped variant of it (your design) as an additional wallpaper once it's ready?

**Comment by hellcp** [comment]
We could also leave this design for what comes next after Leap, and do the usual refresh on the next major release (and then sync up to Tumbleweed)

**Comment by hellcp** [comment]
Thinking of something along these lines for Tumbleweed variant, and possibly a MicroOS Desktop variant with purple theme
![falling-tumbleweed-full-soft-coloured-light](https://user-images.githubusercontent.com/30577011/188007172-588d1604-e692-4cd5-9723-0456140d1472.png)
![falling-microos-full-soft-coloured-light](https://user-images.githubusercontent.com/30577011/188007451-d6871fab-2425-49fb-84b2-2ed6aa85971c.png)

**Comment by sysrich** [comment]
I dont hate the Tumbleweed one, I do really really REALLY dislike the purple of the MicroOS one (like, dislike it so much I'll veto package submissions including it...)

I think both the TW and MicroOS one would benefit from a reduction in saturation and perhaps the addition of some kind of softening, depth of field, or otherwise blurring to somewhat soften all those hard edges

Both the TW and the MicroOS ones are far busier than the Leap/SLE one, and I dislike that..I think the Leap/SLE proportion of 'plain to noise' ratio is much better for a default wallpaper

**Comment by hellcp** [comment]
Yeah, noted, I do agree with most of that. I will likely also work on a dark mode variant for both, since it would be nice to have that

**Comment by hellcp** [comment]
Making the entire image less contrasty should fix some of these issues I think, do you think this is the right direction?
![falling-tumbleweed-light](https://user-images.githubusercontent.com/30577011/188121611-390f24fe-d156-4239-9041-a467c2b932b7.png)
![falling-microos-light](https://user-images.githubusercontent.com/30577011/188121853-8cc2a8fd-18bc-4d99-89a9-f793c8239610.png)
![falling-leap-light](https://user-images.githubusercontent.com/30577011/188121613-023bab68-dfb5-48c5-b33e-a934e8008d8b.png)

**Comment by lkocman** [comment]
@hellcp I do like these, but we need to get the yellow one right. To me the yellow variant still hurts eyes a bit to look into the yellow especially after watching darker background first. Perhaps the yellow should be always on mostly dark background (e.g. yellow on gray). Otherwise I do like the purlple and cyan ones.

**Comment by lkocman** [comment]
Hello team I did split the next-gen Factory and ALP branding into a separate issue
https://github.com/openSUSE/branding/issues/135

**Comment by lkocman** [comment]
Merged scaled variants of this, @hellcp came up with logo placemend guideline, so that was corrected compared to last proposal in this issue.

![desktop-1920x1080](https://user-images.githubusercontent.com/510119/189629990-3ed4ac5c-0783-4dfd-a93b-2998900a0aa5.svg)

**Comment by lkocman** [comment]
Closing the issue
