### ISSUE TITLE
Leap 16 and Factory abstract wallpaper

### ISSUE THREAD

**Issue by lkocman** [openSUSE/branding#135]
This is for a tracking of work on the refresh of Factory (TW + MicroOS) wallpapers as well as background for ALP.
**5k version shoud be a mandatory requirement, we seemed to have issue wit this in the past. See #116** 

The initial graphics proposal from @hellcp as part of work on openSUSE Leap 15.5 background
https://github.com/openSUSE/branding/issues/132#issuecomment-1235342392

![188121611-390f24fe-d156-4239-9041-a467c2b932b7](https://user-images.githubusercontent.com/510119/188396472-20c9c340-2036-44f0-b9e4-ad05a2ab3f3e.png)

![188121613-023bab68-dfb5-48c5-b33e-a934e8008d8b](https://user-images.githubusercontent.com/510119/188396468-5a94ac6a-b828-4f5c-8f74-3fb3dbf26d2a.png)
![188121853-8cc2a8fd-18bc-4d99-89a9-f793c8239610](https://user-images.githubusercontent.com/510119/188396470-896fcb3f-bd5c-45c4-8406-f0bf04ac5d2c.png)

**Comment by sysrich** [comment]
Definately more in the right direction IMHO...and with this lower contrast I can actually imagine the purple one being darker purple, as long as the contrast doesn't increase :)

**Comment by hellcp** [comment]
I think this is a good colour for the light theme variant, I will experiment more with darker purples with the dark mode version most likely

**Comment by lkocman** [comment]
@hellcp I did a small proposal of co-ordination of efforts in between us and SUSE's branding team. It would be perfect if the first ALP desktop prototype from SUSE would be based already on this new set. I'm not sure when to expect it though.

**Comment by hellcp** [comment]
I am assuming SUSE team that's working on that knows how to communicate with us, would be nice to see communication besides just co-coordination :P

**Comment by lkocman** [comment]
Good idea is to avoid usage of adobe-source-sans for wallpaper as this kinda kills minimal desktop installations. @sysrich mentioned it adds up to 400 megs.
https://bugzilla.opensuse.org/show_bug.cgi?id=1203394

Perhaps something we should re-think in our https://opensuse.github.io/branding-guidelines/

**Comment by lkocman** [comment]
I really believe that we should consider https://hackweek.opensuse.org/22/projects/opensuse-12-dot-1-dvd-art for being the ultimate wallpaper. It has a great idea and spirit. It could be perhaps also digitalized.

![geeko-dvd-mosaic-600 (1)](https://user-images.githubusercontent.com/510119/219432131-cbfc25ae-e0a2-483d-b498-03bb468caafb.jpg)

**Comment by hellcp** [comment]
It would be against our [wallpaper guidelines](https://en.opensuse.org/openSUSE:Artwork_guidelines#Wallpapers)

**Comment by tserong** [comment]
Thanks @lkocman, I'd be delighted if there's some way my geeko art could be used, although I'm not sure how to make it meet the guidelines @hellcp mentioned.

**Comment by tserong** [comment]
Well, you can obviously fade things away to make images unobtrusive like the guidelines say, I'm just not sure that's the right approach for this particular piece...

![image](https://user-images.githubusercontent.com/754700/219550432-bf66359c-1ce6-4189-a737-3c83b6874206.png)

**Comment by hellcp** [comment]
That seems even worse, the point of those guidelines is not to have objects on the desktop that draw unnecessary attention, so having a wallpaper that's just geeko or just a lightbulb or any other single object is not going to be acceptable. We do have secondary wallpapers that never landed in the distro though, so if you want to revive that project, go ahead and work out packaging and distribution of the [openSUSE/wallpapers](https://github.com/openSUSE/wallpapers) repo

**Comment by tserong** [comment]
> That seems even worse, the point of those guidelines is not to have objects on the desktop that draw unnecessary attention, so having a wallpaper that's just geeko or just a lightbulb or any other single object is not going to be acceptable.

Right, makes sense.

> We do have secondary wallpapers that never landed in the distro though, so if you want to revive that project, go ahead and work out packaging and distribution of the [openSUSE/wallpapers](https://github.com/openSUSE/wallpapers) repo

OK, I did not know about that project, thanks for the pointer.

**Comment by tserong** [comment]
JFTR in the meantime I've put my original photos plus a couple of wallpaper JPGs in https://github.com/tserong/hackweek22

**Comment by cuphi** [comment]
> I really believe that we should consider https://hackweek.opensuse.org/22/projects/opensuse-12-dot-1-dvd-art for being the ultimate wallpaper. It has a great idea and spirit. It could be perhaps also digitalized.
> 
> ![geeko-dvd-mosaic-600 (1)](https://user-images.githubusercontent.com/510119/219432131-cbfc25ae-e0a2-483d-b498-03bb468caafb.jpg)
![opensuse_large](https://user-images.githubusercontent.com/97068372/220655698-f42018a3-eb03-4ef5-a9e6-046cf7eb3de7.jpg)

I ran it through Cupscale and used The GIMP to change the dimensions to 5120x3840.  Now you have it big.  Enjoy.

**Comment by clanig** [comment]
After I read about the openSUSE default wallpaper as "inanimate" in a forum, and kind of feeling what the person meant by that statement, I decided to ask DALL-E for help by providing it with some instructions and got a result that might be more satisfying. I think changing the wallpaper is an easy thing and if it makes users more motivated to work with openSUSE, why not?

Unfortunately DALL-E does not provide a high resolution result. Here is a modified, post processed version of it that should look OK on up to 4K screens:

![opensuse_tumbleweed_desert_with_logo_3840x2160](https://github.com/openSUSE/branding/assets/31621613/c3398025-4f10-472f-b753-74940bf44955)

I noticed that apparently we only use scalable vector graphics here - if that is the case such wallpapers as above are not possible unfortunately.

**Comment by hellcp** [comment]
That also doesn't follow the wallpaper guidelines linked before

**Comment by clanig** [comment]
Thanks for your reply. You are right, and thanks for pointing it out. And I do get the point of having these guidelines. However, it looks to me like the expectation of some people would be more toward having something entertaining or interesting on their desktop which is clearly visible.
Given that users can change the background, personally I would even say, as long as they like it in the first seven days after the installation I would be fine with it.

From a gut feeling, I would pretty much try to balance low contrast areas and content on a wallpaper. So if it was up to me, I would not make the guidelines that strict. Just to leave the opinion here.

**Comment by hellcp** [comment]
We do offer additional set of wallpapers for that purpose, however that's not what this is about. This is about the default wallpaper, which is meant to be low contrast. That doesn't mean that the wallpaper can't be humorous, the current Tumbleweed and Leap wallpapers cause a lot of people smile when they see the toilets on there.

**Comment by lkocman** [comment]
Hello team,

I started a discussion with SUSE Branding team, regarding Leap 16 wallpaper collection

![image](https://github.com/openSUSE/branding/assets/510119/cc477fed-b60e-410b-96fe-e9a1bda82878)
![image](https://github.com/openSUSE/branding/assets/510119/574da4b8-8f16-4eef-93e6-c1f1a237088a)

I'll keep you posted as soon as I have some new information.
The idea is to have 5 wallpapers, and at least three of them could be shared with other openSUSE distributions (photos + openSUSE project abstract wallpaper)

**UPDATE: issue was rejected by SUSE brand team, as they are not working on openSUSE requests.**

**Comment by lkocman** [comment]
![image](https://github.com/openSUSE/branding/assets/510119/95a5ed6d-c722-4e9d-9740-b4c095d8e64d)

**Comment by lkocman** [comment]
Ideas from Leap 16 branding workshop on osc2024
(day and night variant from lkocman, clouds or start constellations making the logo, tent has light on at night)

![image](https://github.com/openSUSE/branding/assets/510119/383ef479-9af9-43ab-93d0-8952cc0e59b5)
![image](https://github.com/openSUSE/branding/assets/510119/28c2401c-3e6d-4068-a456-677094f59658)

**Comment by lkocman** [comment]
Ideas from Leap 16 branding workshop on osc2024
(desert/jungle day and night variants from TamarG)

![image](https://github.com/openSUSE/branding/assets/510119/eda38724-f6e9-4065-a342-5f7775beb23b)
![image](https://github.com/openSUSE/branding/assets/510119/aa85aefe-4761-4223-b358-7704a9e7b175)
![image](https://github.com/openSUSE/branding/assets/510119/d4727340-53cb-434d-92ef-36e258cb84a9)
![image](https://github.com/openSUSE/branding/assets/510119/c891d117-b352-488e-9a17-e51b80bb6940)

**Comment by lkocman** [comment]
Ideas from Leap 16 branding workshop on osc2024
distro specific variantions from mcalabkova 

![20240704_220526](https://github.com/openSUSE/branding/assets/510119/9c2228c7-7416-4153-9a89-d47261afba22)
![20240704_220511 (1)](https://github.com/openSUSE/branding/assets/510119/0a0f7000-5d33-4ece-868c-10d8354649bf)

**Comment by lkocman** [comment]
Ideas from Leap 16 branding workshop on osc2024
Bernhard'ss geometric/lizzard skin experiment

![image](https://github.com/openSUSE/branding/assets/510119/5e49b22f-3bd9-42a7-a602-6d17ec81e272)

**Comment by armync** [comment]
@lkocman After the logo design contest, no decision was reached. In your request to the SUSE team, you've linked the currently available logos (though I see a reference as "new Leap logo"). Has there been no decision to adopt a single unitary design for all distributions?

The Leap logo, for instance, uses the older, square-shaped style. Some distributions have adopted the pprmint proposals (indeed based on hellcp's designs) which are more naturally curved/rounded. Why wouldn't openSUSE consider replacing the older logos with pprmint's designs across all distributions? 

While I understand the contest entries may not have been that ideal, I regard as true that pprmint designs are the most suitable among existing options (at least for the distributions; on main logo, Giga's design was closer to the desired concept and practically based on SUSE's newer style). 

The current situation is a bit messy, with different styles being used across distributions.

**Comment by lkocman** [comment]
@ArmynC Leap adopted the new logo elected by community check https://github.com/openSUSE/branding/tree/leap-15.6/raw-theme-drop as well as logo.svg in the directory, distribution itself has it too. I can't really speak for other distros.

**Comment by lkocman** [comment]
Quick drop of abstract bg from @hellcp (I've recreated submissions from discussed in #132.
The dark one uses multiple colors (transparency, swatches), imho it looks really cool.

![dark-preview](https://github.com/openSUSE/branding/assets/510119/44701aa0-4a7f-4a0e-9a86-1431eb4dc6fe)
![light-preview](https://github.com/openSUSE/branding/assets/510119/52e745ba-8721-4488-8386-0231855e5d0e)

I've submitted already PR  #154 for 16 so we have something in openQA already.

**Comment by armync** [comment]
> @ArmynC Leap adopted the new logo elected by community check https://github.com/openSUSE/branding/tree/leap-15.6/raw-theme-drop as well as logo.svg in the directory, distribution itself has it too. I can't really speak for other distros.

I get it now. So there was no in-between teams coordination, strange. It's a pity it wasn't taken into account at voting to consider the options based on the Full Design Themes (not individual ones) and with last key-decision by the team. It was flawed from begging imho.

**Comment by lkocman** [comment]
@ArmynC I have understanding for your concerns, but let's stay constructive and focus on the acutal issue that you're commenting on. I think #93  might be a place for such discussions.

This issue is specifically for the Leap 16 wallpaper refresh (and hopefully joined TW wallpaper refresh too) let's keep discussion to the point, share proposals, experiment with them and drive issue to resolution.

**Comment by hellcp** [comment]
> I get it now. So there was no in-between teams coordination, strange. It's a pity it wasn't taken into account at voting to consider the options based on the Full Design Themes (not individual ones) and with last key-decision by the team. It was flawed from begging imho.

The only logo that doesn't really fit in with the other designs is Tumbleweed, and the reason why that hasn't changed yet is down to the fact none of the logos created by the community met the expectations of the voters. Tumbleweed is going to get a new logo at some point though, we just need to find something better

**Comment by tmrnd0** [comment]
Here is Lubos camping chameleon idea both in day and night: 
![CampingChameleonDia](https://github.com/user-attachments/assets/2ed45b40-74cc-4a4b-add3-46e43d626f9d)
![CampingChameleonNoche](https://github.com/user-attachments/assets/8c9cbdc8-67d0-4fed-a9c1-08dd6f82b61f)
![CampingChameleonMasNoche](https://github.com/user-attachments/assets/2652f0c0-e998-4d1b-b6ae-9f4ab84a7a52)

**Comment by lkocman** [comment]
Resolved as part of Pull #154 and #160. Other wallpapers aside from Distro specific abstract wallpapers will be handled in their respective Issues.
