### ISSUE TITLE
Limesurvey fruity_openSUSE theme is not working well in darkmode

### ISSUE THREAD

**Issue by lkocman** [openSUSE/branding#143]
Hello

I did use the Fruity_openSUSE theme and the enforced green font isn't ideal on Dark theme. 

I think it would be the best to leave font on automatic color or adapt it more to the bootswatch theme which uses higher constract in between font and background.

![fruity_theme](https://github.com/openSUSE/branding/assets/510119/244ee035-220e-4899-a11a-01733fece8fe)
![image](https://github.com/openSUSE/branding/assets/510119/3037a01c-ad6e-48b3-9903-071b6f50df38)

**Comment by hellcp** [comment]
I suspect you will get a faster response if you report it on progress, afaik this was made by Lars

**Comment by lkocman** [comment]
Oky closing then. Thank you @hellcp
