### ISSUE TITLE
Distribution agnostict wallpaper for all of our distributions

### ISSUE THREAD

**Issue by lkocman** [openSUSE/branding#156]
Aeon inspired gradient SVG. 4096x4096 as per #161 
As it is it scales nice on 16:10 / 16:9 ratio (most of usecases)

PNG
![project-square](https://github.com/user-attachments/assets/7ccb89eb-f945-49cb-98b5-82563b7b48bc)

SVG
![project-square](https://github.com/user-attachments/assets/6d414d14-0547-496f-9edb-910aeb7c79b3)

**Comment by lkocman** [comment]
@sysrich  had no objection to reuse his work as it's open source

Since we store SVG I tried to recreate his pattern from https://build.opensuse.org/source/devel:microos:aeon/gnome-branding-Aeon/aeonwallpaper.png

(for eye comparison)
![image](https://github.com/user-attachments/assets/0b86d1a6-039a-4f39-927b-951173e44c3b)

**Comment by hellcp** [comment]
I have a feeling that using Aeon green is a bad idea for a distro agnostic wallapaper, since it does imply Aeon pretty strongly

**Comment by lkocman** [comment]
@hellcp what do you recommend  as a base color?

**Comment by lkocman** [comment]
Here my SVG remake (with bunch of filters from youtube tutorials to smoothen then gradient) + generated PNG from it

svg
![aeon-gradient](https://github.com/user-attachments/assets/8bbff6e0-fe99-4829-a819-74802185a708)


png
![aeon-gradient](https://github.com/user-attachments/assets/4906ec97-bb0d-4902-9fbb-a680b21eb2ff)

**Comment by lkocman** [comment]
Experimental alernative using colors we use e.g. for TW on get-o-o or in branding guidelines

![image](https://github.com/user-attachments/assets/14e7118b-ec4d-4c46-8cc8-1062b934e1ec)

**Comment by lkocman** [comment]
Alternative placement (based on font color in our branding guidelines)

![geekos-gradient](https://github.com/user-attachments/assets/04fcb75b-6d3f-4fe0-9a86-9da27299a99f)

**Comment by lkocman** [comment]
I still like the green touch on Aeon better.

**Comment by tmrnd0** [comment]
I like both green hues a lot.

**Comment by lkocman** [comment]
I've used this pattern for one of proposals for the #158 
![jungle-pattern](https://github.com/user-attachments/assets/1574073b-ff80-482b-843c-9aba353c5aad)

with actual logo

![ari-jungle-spin](https://github.com/user-attachments/assets/f8b11d78-ea3e-4ecc-a239-f78289ab88a2)

**Comment by lkocman** [comment]
Generally I received feedback that this one is a way to go. Also Doug already used it in one of posts.

SVG

![geekos-gradient](https://github.com/user-attachments/assets/05d14fe1-1701-4b50-94fa-88b3e120c69c)

PNG

![geekos-gradient](https://github.com/user-attachments/assets/51f298d9-3f2e-405f-8ad0-d30792087922)

**Comment by lkocman** [comment]
I wonder if I should make also yellow edition for Leap. Might be a better fit.

**Comment by lkocman** [comment]
Thoughts @hellcp ? Also whould I simply place this one aside from others in the raw-theme-drop dir?

**Comment by hellcp** [comment]
Sure

**Comment by lkocman** [comment]
I will most likely rework this one to 4096x4096 too. It will be stored in https://github.com/openSUSE/wallpapers

**Comment by lkocman** [comment]
Closing with https://github.com/openSUSE/wallpapers/pull/19
