### ISSUE TITLE
Missing /usr/share/default-dark.png symlink

### ISSUE THREAD

**Issue by lkocman** [openSUSE/branding#166]
I think it would make a lot of sense to add the default-dark.png symlink to the topdir.

```
test@localhost:/usr/share/wallpapers> ls -la
total 20
drwxr-xr-x 1 root root  222 Oct  1 17:31 .
dr-xr-xr-x 1 root root 6304 Oct  1 17:21 ..
lrwxrwxrwx 1 root root   22 Oct  1 11:15 default.png -> openSUSEtumbleweed.png
-rw-r--r-- 1 root root   96 Oct  1 17:29 default.png.desktop
drwxr-xr-x 1 root root   70 Oct  1 17:21 openSUSEdefault
lrwxrwxrwx 1 root root   43 Oct  1 11:15 openSUSEtumbleweed.png -> openSUSEdefault/contents/images/default.png
-rw-r--r-- 1 root root  110 Oct  1 17:29 openSUSEtumbleweed.png.desktop
lrwxrwxrwx 1 root root   15 Oct  1 11:15 SLEdefault -> openSUSEdefault
drwxr-xr-x 1 root root  580 Oct  1 12:11 xfce
```

**Comment by lkocman** [comment]
This should be a quick fix in spec https://build.opensuse.org/package/show/Base:System/branding-openSUSE
so anybody who'd like to learn packaging can jump on this one :-)

Needs to be fixed also for https://build.opensuse.org/package/show/openSUSE:Leap:16.0/branding-openSUSE

**Comment by Suraj-kumar00** [comment]
Hi @lkocman, how have you been?
I would like to work on this issue. But can you please help me to understand what to do in this issue in order resolve this?
So far understand that default-dark.png is missing at :/usr/share/wallpapers path right?

**Comment by lkocman** [comment]
Closing, thank you @tacerus
