### ISSUE TITLE
Password prompt not centered

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/branding#58]
Using the new label-ft plugin (https://bugzilla.opensuse.org/show_bug.cgi?id=959986) the password prompt shown when a crypt device is being mounted is not centered. It's only a minor issue with short names, but on my laptop I've got a rather long name so it doesn't even fit on screen, although there is enough space on the left.
![screenshot_mcbrain-1_2016-01-21_10 29 33](https://cloud.githubusercontent.com/assets/1622084/12476611/dec04fc6-c02a-11e5-8db6-602383494211.png)

**Comment by tigerfoot** [comment]
Two remarks, we should place the label inside the prompt box
could we reduce uneeded words , and for example use the same string as the pure text dialog box?

**Comment by Vogtinator** [comment]
Placing the label inside the prompt box might not be easy, as the box is a static picture and the string has variable width. The text is supplied by systemd (systemd-ask-password).

**Comment by tigerfoot** [comment]
I've forget how much svg is missing in plymouth :-)

**Comment by LelCP** [comment]
Fixed with commit #65
